module.exports = {
  extends: ['eslint:recommended', 'prettier'],
  rules: {
    eqeqeq: 'error',
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'no-console': 'warn',
    'no-else-return': 'error',
    'no-implicit-coercion': 'error',
    'no-lonely-if': 'error',
    'no-magic-numbers': [
      'error',
      { enforceConst: true, ignore: [-1, 0, 1], ignoreDefaultValues: true },
    ],
    'no-negated-condition': 'error',
    'no-nested-ternary': 'error',
    'no-restricted-properties': [
      'error',
      { object: 'describe', property: 'only' },
      { object: 'it', property: 'only' },
    ],
    'no-return-assign': 'error',
    'no-return-await': 'error',
    'no-sequences': 'error',
    'no-shadow': 'warn',
    'no-unmodified-loop-condition': 'warn',
    'no-unneeded-ternary': 'error',
    'no-useless-computed-key': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'object-shorthand': 'error',
    'one-var': ['error', 'never'],
    'operator-assignment': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': 'error',
    'prefer-exponentiation-operator': 'error',
    'prefer-object-spread': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-await': 'error',
    'require-yield': 'error',
    'sort-keys': 'warn',
    'spaced-comment': ['error', 'always', { markers: ['/'] }],
    strict: ['error', 'global'],
    yoda: 'error',
  },
};
